server:
  port: 8089
spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.23.50.36:3306/trademark?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Yswg@erp300
    # hikari 数据源专用配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  # jpa 相关配置
  jpa:
    hibernate:
      ddl-auto: update
    #打印sql
    show-sql: false
    # 数据库方言
    database-platform: org.hibernate.dialect.MySQLDialect

  # es 配置
  elasticsearch:
    rest:
      uris: 8.129.121.226:9202  #8.129.121.226:9202  120.77.232.73:9202
      username: es_user
      password: elasticsearch2021.+
    data:
      elasticsearch:
        repositories:
          enabled: true
        cluster-nodes: 8.129.121.226:9300 #8.129.121.226:9300  120.77.232.73:9300
        cluster-name: my-elastic
  # mvc 静态资源映射
  mvc:
    static-path-pattern: /**

  # 静态资源热部署
  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: static/**

  # 日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


